Add Downloads page update to changelog
broadinstitute/gnomad-blog pull request #108
Opened 2023-02-01 21:50 UTC by rileyhgrant

Adds a changelog entry for the update to the Downloads page. To be merged/pushed to production when the corresponding browser PR gets merged.

2023-02-03 14:24 UTC, ch-kr approved these changes
minor rewording comment but LGTM!

2023-02-03 14:24 UTC, ch-kr commented on content/changelog/2023-02-updated-downloads-page.md
> +The [downloads page](https://gnomad.broadinstitute.org/downloads)'s format has been updated. The set of tabs that previously separated individual release's download links has been replaced by a stick
"see what datasets are available for download at a glance" reads a bit better, but I'm not sure it conveys the same message. maybe "see what datasets are available for download" is enough here, though -- what do you think?

2023-02-03 17:21 UTC, mattsolo1 requested changes
Going to change a bit of the wording here, 1 sec.

2023-02-03 18:25 UTC, mattsolo1 commented
We have redesigned the gnomAD [Downloads Page](https://gnomad.broadinstitute.org/downloads) to make it easier to explore datasets released by the gnomAD production team and gnomAD-affiliated research groups. 

Previously, our major releases (gnomAD v2, gnomAD v3, and ExAC) were organized under tabs that users would click to see which datasets were available for each release. This tab-based navigation scheme made it difficult to quickly understand the information hierarchy on the page. It also prevented users from searching the page using the standard internet browser search functionality (CTRL + F).

Now, instead of tabs, the new layout features a table of contents on the righthand side. Users will have a better sense of what is available and can quickly jump to specific releases and datasets. To help maintain a sense of context, the table of contents synchronizes with the page position as the user scrolls. Since all text is on the same page, CTRL-F searching is now possible.

Furthermore, the new Downloads Page attempts to distinguish which datasets are produced by the gnomAD production team ("Core Dataset") from downstream analyses carried out by affiliated research groups ("Secondary Analyses"). For example, our recently released [Genomic Constraint](https://gnomad.broadinstitute.org/downloads#research-genomic-constraint) analysis falls into the latter category.

2023-02-09 18:13 UTC, mattsolo1 commented
Btw if anyone feels my edit is too wordy... feel free to discard. Don't let this hold you up.

2023-02-09 18:13 UTC, mattsolo1 approved these changes

2023-02-15 17:17 UTC, merged